(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Standard Model + Kinetic Mixing Vector + Dark Matter",
  Authors -> {"Logan A. Morrison"},
  Version -> "1.0.0",
  Date -> "24. 01. 2020",
  Institutions -> {"University of California, Santa Cruz"},
  Emails -> {"loanmorr@ucsc.edu"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {NP, 0}, {NPMIX, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

V[5] == {
    SelfConjugate -> True,
    PropagatorLabel -> "V",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MV,
    Indices -> {} },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

F[5] == {
    SelfConjugate -> False,
    PropagatorLabel -> "~chi",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MDM,
    Indices -> {} },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Go",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ V[5] ] = 1;
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
MV[ ___ ] := MV;
Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
MDM[ ___ ] := MDM;
MH[ ___ ] := MH;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{((-3*I)*MH^2)/vev^2, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{((-I)*MH^2)/vev^2, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{((-2*I)*MH^2)/vev^2, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{((-I)*MH^2)/vev^2, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{((-I)*MH^2)/vev^2, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{((-3*I)*MH^2)/vev^2, 0}},

C[ S[2] , S[2] , S[1] ] == {{((-I)*MH^2)/vev, 0}},

C[ S[3] , -S[3] , S[1] ] == {{((-I)*MH^2)/vev, 0}},

C[ S[1] , S[1] , S[1] ] == {{((-3*I)*MH^2)/vev, 0}},

C[ S[3] , -U[31] , U[2] ] == {{((-I/4)*EL^2*(cw - sw)*(cw + sw)*vev)/(Sqrt[2]*cw*sw^2), 0}},

C[ S[3] , -U[2] , U[32] ] == {{((I/4)*EL^2*(cw^2 + sw^2)*vev)/(Sqrt[2]*cw*sw^2), 0}},

C[ -S[3] , -U[32] , U[2] ] == {{((-I/4)*EL^2*(cw - sw)*(cw + sw)*vev)/(Sqrt[2]*cw*sw^2), 0}},

C[ -S[3] , -U[2] , U[31] ] == {{((I/4)*EL^2*(cw^2 + sw^2)*vev)/(Sqrt[2]*cw*sw^2), 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-I/8)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[2] , -U[32] , U[32] ] == {{-(EL^2*vev)/(8*sw^2), 0}},

C[ S[2] , -U[31] , U[31] ] == {{(EL^2*vev)/(8*sw^2), 0}},

C[ S[1] , -U[32] , U[32] ] == {{((-I/8)*EL^2*vev)/sw^2, 0}},

C[ S[1] , -U[31] , U[31] ] == {{((-I/8)*EL^2*vev)/sw^2, 0}},

C[ S[3] , -U[31] , U[1] ] == {{((-I/2)*EL^2*vev)/(Sqrt[2]*sw), 0}},

C[ -S[3] , -U[32] , U[1] ] == {{((-I/2)*EL^2*vev)/(Sqrt[2]*sw), 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc22, 0}, {I*gc22, 0}},

C[ -U[1] , U[32] , V[3] ] == {{I*gc23, 0}, {I*gc23, 0}, {0, 0}},

C[ -U[1] , U[31] , -V[3] ] == {{I*gc24, 0}, {I*gc24, 0}, {0, 0}},

C[ -U[32] , U[1] , -V[3] ] == {{I*gc25, 0}, {I*gc25, 0}, {0, 0}},

C[ -U[32] , U[32] , V[1] ] == {{I*gc26, 0}, {I*gc26, 0}, {0, 0}},

C[ -U[32] , U[32] , V[2] ] == {{I*gc27, 0}, {I*gc27, 0}, {0, 0}},

C[ -U[32] , U[2] , -V[3] ] == {{I*gc28, 0}, {I*gc28, 0}, {0, 0}},

C[ -U[31] , U[1] , V[3] ] == {{I*gc29, 0}, {I*gc29, 0}, {0, 0}},

C[ -U[31] , U[31] , V[1] ] == {{I*gc30, 0}, {I*gc30, 0}, {0, 0}},

C[ -U[31] , U[31] , V[2] ] == {{I*gc31, 0}, {I*gc31, 0}, {0, 0}},

C[ -U[31] , U[2] , V[3] ] == {{I*gc32, 0}, {I*gc32, 0}, {0, 0}},

C[ -U[2] , U[32] , V[3] ] == {{I*gc33, 0}, {I*gc33, 0}, {0, 0}},

C[ -U[2] , U[31] , -V[3] ] == {{I*gc34, 0}, {I*gc34, 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc35*SUNF[e1x2, e2x2, e3x2]), 0}, {gc35*SUNF[e1x2, e2x2, e3x2], 0}, {gc35*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc35*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc35*SUNF[e1x2, e2x2, e3x2]), 0}, {gc35*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc36*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc36*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc36*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -S[3] ] == {{gc37L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc37R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[2] ] == {{gc38L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc38R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc39L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc39R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -S[3] ] == {{gc40[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[2] ] == {{gc41L[e1x2, e2x2], 0}, {gc41R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc42L[e1x2, e2x2], 0}, {I*gc42R[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[3] ] == {{gc43L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc43R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[2] ] == {{gc44L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc44R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc45L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc45R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ S[3] , -S[3] , V[1] , V[5] ] == {{(I*EL^2*eps)/cw, 0}},

C[ S[2] , S[1] , V[5] ] == {{-gc47, 0}, {gc47, 0}},

C[ S[3] , -S[3] , V[5] ] == {{(-I)*gc48, 0}, {I*gc48, 0}},

C[ -F[5] , F[5] , V[5] ] == {{I*gc49, 0}, {I*gc49, 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-I/2)*EL^2)/sw, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-EL^2/(2*sw), 0}},

C[ -S[3] , V[1] , V[3] ] == {{-(EL^2*vev)/(2*sw), 0}},

C[ S[2] , -S[3] , V[3] ] == {{(-I)*gc53, 0}, {I*gc53, 0}},

C[ -S[3] , S[1] , V[3] ] == {{-gc54, 0}, {gc54, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc55, 0}, {I*gc55, 0}, {I*gc55, 0}, {(-I)*gc55, 0}, {(-I)*gc55, 0}, {I*gc55, 0}},

C[ S[2] , -S[3] , V[5] , V[3] ] == {{((-I/2)*EL^2*eps)/(cw*sw), 0}},

C[ -S[3] , S[1] , V[5] , V[3] ] == {{-(EL^2*eps)/(2*cw*sw), 0}},

C[ -S[3] , V[5] , V[3] ] == {{-(EL^2*eps*vev)/(2*cw*sw), 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-I/2)*EL^2)/sw, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{EL^2/(2*sw), 0}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ S[2] , S[3] , -V[3] ] == {{(-I)*gc62, 0}, {I*gc62, 0}},

C[ S[3] , S[1] , -V[3] ] == {{-gc63, 0}, {gc63, 0}},

C[ S[2] , S[3] , V[5] , -V[3] ] == {{((-I/2)*EL^2*eps)/(cw*sw), 0}},

C[ S[3] , S[1] , V[5] , -V[3] ] == {{(EL^2*eps)/(2*cw*sw), 0}},

C[ S[3] , V[5] , -V[3] ] == {{(EL^2*eps*vev)/(2*cw*sw), 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*vev)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc71, 0}, {(-I)*gc71, 0}, {(2*I)*gc71, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc72, 0}, {I*gc72, 0}, {I*gc72, 0}, {(-I)*gc72, 0}, {(-I)*gc72, 0}, {I*gc72, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc73, 0}, {(-I)*gc73, 0}, {(2*I)*gc73, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[3] ] == {{0, 0}, {gc74R[e1x2, e2x2], 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , S[1] , V[2] ] == {{-gc76, 0}, {gc76, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc77, 0}, {I*gc77, 0}},

C[ S[2] , S[2] , V[5] , V[2] ] == {{((-I/2)*EL^2*eps*(cw^2 + sw^2))/(cw^2*sw), 0}},

C[ S[3] , -S[3] , V[5] , V[2] ] == {{((I/2)*EL^2*eps*(cw - sw)*(cw + sw))/(cw^2*sw), 0}},

C[ S[1] , S[1] , V[5] , V[2] ] == {{((-I/2)*EL^2*eps*(cw^2 + sw^2))/(cw^2*sw), 0}},

C[ S[1] , V[5] , V[2] ] == {{((-I/2)*EL^2*eps*(cw^2 + sw^2)*vev)/(cw^2*sw), 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{EL^2/(2*cw), 0}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*vev)/(2*cw), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-EL^2/(2*cw), 0}},

C[ S[3] , -V[3] , V[2] ] == {{-(EL^2*vev)/(2*cw), 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc88, 0}, {I*gc88, 0}, {I*gc88, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc93, 0}, {(-I)*gc93, 0}, {(2*I)*gc93, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc94*IndexDelta[e1x2, e2x2], 0}, {I*gc94*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc95*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc95*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc96*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc96*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc97*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc97*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc98*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc98*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[5] ] == {{I*gc99*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[5] ] == {{I*gc100L*IndexDelta[e1x2, e2x2], 0}, {I*gc100R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[5] ] == {{I*gc101L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc101R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[5] ] == {{I*gc102L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc102R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc103[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc104[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc105*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc106*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc107L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc107R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc108L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc108R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc109*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc110L*IndexDelta[e1x2, e2x2], 0}, {I*gc110R*IndexDelta[e1x2, e2x2], 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc22 -> -EL,
     gc23 -> EL,
     gc24 -> -EL,
     gc25 -> EL,
     gc26 -> -EL,
     gc27 -> -((cw*EL)/sw),
     gc28 -> (cw*EL)/sw,
     gc29 -> -EL,
     gc30 -> EL,
     gc31 -> (cw*EL)/sw,
     gc32 -> -((cw*EL)/sw),
     gc33 -> (cw*EL)/sw,
     gc34 -> -((cw*EL)/sw),
     gc35 -> -GS,
     gc36 -> -GS^2,
     gc37L[e1x2_, e2x2_] -> IndexSum[Conjugate[CKM[e2x2, Generation$1]]*Conjugate[yd[Generation$1, e1x2]], {Generation$1, 1, 3}],
     gc37R[e1x2_, e2x2_] -> -IndexSum[Conjugate[CKM[Generation$1, e1x2]]*yu[Generation$1, e2x2], {Generation$1, 1, 3}],
     gc38L[e1x2_, e2x2_] -> -(Conjugate[yd[e2x2, e1x2]]/Sqrt[2]),
     gc38R[e1x2_, e2x2_] -> yd[e1x2, e2x2]/Sqrt[2],
     gc39L[e1x2_, e2x2_] -> -(Conjugate[yd[e2x2, e1x2]]/Sqrt[2]),
     gc39R[e1x2_, e2x2_] -> -(yd[e1x2, e2x2]/Sqrt[2]),
     gc40[e1x2_, e2x2_] -> Conjugate[yl[e2x2, e1x2]],
     gc41L[e1x2_, e2x2_] -> -(Conjugate[yl[e2x2, e1x2]]/Sqrt[2]),
     gc41R[e1x2_, e2x2_] -> yl[e1x2, e2x2]/Sqrt[2],
     gc42L[e1x2_, e2x2_] -> -(Conjugate[yl[e2x2, e1x2]]/Sqrt[2]),
     gc42R[e1x2_, e2x2_] -> -(yl[e1x2, e2x2]/Sqrt[2]),
     gc43L[e1x2_, e2x2_] -> IndexSum[CKM[Generation$1, e2x2]*Conjugate[yu[Generation$1, e1x2]], {Generation$1, 1, 3}],
     gc43R[e1x2_, e2x2_] -> -IndexSum[CKM[e1x2, Generation$1]*yd[Generation$1, e2x2], {Generation$1, 1, 3}],
     gc44L[e1x2_, e2x2_] -> Conjugate[yu[e2x2, e1x2]]/Sqrt[2],
     gc44R[e1x2_, e2x2_] -> -(yu[e1x2, e2x2]/Sqrt[2]),
     gc45L[e1x2_, e2x2_] -> -(Conjugate[yu[e2x2, e1x2]]/Sqrt[2]),
     gc45R[e1x2_, e2x2_] -> -(yu[e1x2, e2x2]/Sqrt[2]),
     gc47 -> (EL*eps)/(2*cw),
     gc48 -> -(EL*eps)/(2*cw),
     gc49 -> gVXX,
     gc53 -> EL/(2*sw),
     gc54 -> -EL/(2*sw),
     gc55 -> EL,
     gc62 -> -EL/(2*sw),
     gc63 -> -EL/(2*sw),
     gc71 -> -EL^2,
     gc72 -> (cw*EL)/sw,
     gc73 -> EL^2/sw^2,
     gc74R[e1x2_, e2x2_] -> -yl[e1x2, e2x2],
     gc76 -> -(EL*(cw^2 + sw^2))/(2*cw*sw),
     gc77 -> -(cw*EL)/(2*sw) + (EL*sw)/(2*cw),
     gc88 -> (cw*EL^2)/sw,
     gc93 -> -((cw^2*EL^2)/sw^2),
     gc94 -> -EL,
     gc95 -> (2*EL)/3,
     gc96 -> -EL/3,
     gc97 -> GS,
     gc98 -> GS,
     gc99 -> -(EL*eps)/(2*cw),
     gc100L -> -(EL*eps)/(2*cw),
     gc100R -> -((EL*eps)/cw),
     gc101L -> (EL*eps)/(6*cw),
     gc101R -> (2*EL*eps)/(3*cw),
     gc102L -> (EL*eps)/(6*cw),
     gc102R -> -(EL*eps)/(3*cw),
     gc103[e1x2_, e2x2_] -> (EL*CKM[e1x2, e2x2])/(Sqrt[2]*sw),
     gc104[e1x2_, e2x2_] -> (EL*Conjugate[CKM[e2x2, e1x2]])/(Sqrt[2]*sw),
     gc105 -> EL/(Sqrt[2]*sw),
     gc106 -> EL/(Sqrt[2]*sw),
     gc107L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc107R -> (-2*EL*sw)/(3*cw),
     gc108L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc108R -> (EL*sw)/(3*cw),
     gc109 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc110L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc110R -> (EL*sw)/cw};

